if(!isServer)exitWith{};sleep 15;
Q_checks=[];Q_check={params["_name","_pass",["_detail",[]]];Q_checks pushBack[_name,_pass,_detail];diag_log format["[AF_CHECK] %1",[_name,_pass,_detail]]};
Q_group={params["_side"];private _g=createGroup[_side,true];_g setVariable["FST_HC_blacklisted",true,true];_g};
Q_unit={params["_g","_class","_pos"];private _u=_g createUnit[_class,_pos,[],0,"NONE"];_u allowDamage false;_u setDir 0;_u setVariable["Q_shots",0];_u setVariable["Q_rockets",0];_u addEventHandler["Fired",{params["_u","_w"];if(_w=="FST_RPS6HP")then{_u setVariable["Q_rockets",(_u getVariable["Q_rockets",0])+1]};_u setVariable["Q_shots",(_u getVariable["Q_shots",0])+1];if(isNil{_u getVariable "Q_first"})then{_u setVariable["Q_first",time]};diag_log format["[AF_SHOT] %1",[netId _u,typeOf _u,_w,time]]}];_u};
Q_target={params["_pos"];private _g=[west]call Q_group;_g setVariable["BURNS_exempt",true,true];private _u=[_g,"B_Soldier_F",_pos]call Q_unit;_u disableAI "ALL";_u};
setDate[2035,6,15,12,0];0 setFog 0;0 setOvercast 0;
diag_log format["[AF_WORLD_SIZE] %1",worldSize];
diag_log "[AF_COMPILE_BEGIN]";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_addEditableObjects.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_addObjective.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_applyUnitLoadoutSafe.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_burnsAcquirePointFire.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_burnsApplyRole.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_burnsArmorAssist.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_burnsArmorPulseEnd.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_burnsArtillery.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_burnsB1Advance.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_burnsB1Eligible.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_burnsB1Formation.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_burnsB1Hit.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_burnsBXTask.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_burnsCancelAdvanceMove.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_burnsCommand.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_burnsCuratorWaypoint.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_burnsDialog.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_burnsEngagementAllowed.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_burnsGulantharSlope.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_burnsInitEngagement.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_burnsIsDown.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_burnsPatrol.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_burnsPointFire.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_burnsPositions.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_burnsReaction.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_burnsRecoverStations.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_burnsReleaseAdvance.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_burnsReleaseAdvanceUnit.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_burnsReleaseBX.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_burnsReleasePointFire.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_burnsReleaseStation.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_burnsRequest.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_burnsReservePositions.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_burnsRestoreGroupRole.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_burnsRestoreRole.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_burnsRole.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_burnsRushTarget.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_burnsSimulation.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_burnsSpecialTick.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_burnsStateGet.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_burnsStateSet.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_burnsSuppressed.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_burnsSuspendTask.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_burnsTaskInterval.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_burnsUseCover.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_burnsVehicleProgress.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_burnsVisibility.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_burnsVisibleContact.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_captureTransferState.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_catchUntracked.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_checkObjectives.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_cleanupDeadGroups.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_cleanupGroups.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_combatTaskTick.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_createGroupLocal.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_debugDraw.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_emergencyRedistribute.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_emergencyStabilizeDroid.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_emergencyStabilizeGroup.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_enforceDroidStance.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_fillGarrison.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_fpsMonitor.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_frontlineSpawn.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_getFSTOpforUnitOptions.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_getSpawnTarget.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_getVehicleHC.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_handleDisconnect.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_handleZeusOriginalDecision.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_initCombatTasks.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_initDroidCorpseCleanup.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_initEmergencyDroidBandaid.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_initExplosionDiag.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_initHCSystem.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_initSuppression.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_initVisibility.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_interceptZeusPlace.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_isAuthorizedCaller.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_isBlacklisted.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_isDroidUnit.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_isPlayerControlledUnit.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_isProtectedVehicleGroup.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_isSafeGarrisonPos.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_isValidFSTOpforUnit.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_isVehicleTransferSafe.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_legacyRespawnGroup.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_processTransfers.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_qrfBuildLocal.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_qrfSpawn.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_queueNativeModule.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_queueZeusGroup.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_reapplyGarrison.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_receiveTransferState.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_recountUnits.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_registerBurnsEvents.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_registerBurnsModules.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_registerEvents.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_registerHC.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_registerNativeModule.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_registerZenModules.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_requestDeadGroupCleanup.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_requestDebugSnapshot.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_requestFillGarrison.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_requestTransferState.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_sendToVehicleHC.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_setCombatTask.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_spawnGroupOnTarget.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_spawnVehicleOnTarget.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_statusReport.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_trackGroup.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_transferGroup.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\fn_zeusHold.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\XEH_postInit.sqf";
compile preprocessFileLineNumbers "\FST_HCSpawn\XEH_preInit.sqf";
diag_log "[AF_COMPILE_END]";
["AT range15 loaded",getNumber(configFile>>"CfgWeapons">>"FST_RPS6HP">>"Single">>"minRange")==15]call Q_check;
["Ambush module registered",isClass(configFile>>"CfgVehicles">>"FST_BURNS_Module_ambush")]call Q_check;
Q_at=[];
{
 private _range=_x;private _p=[1000+2000*_forEachIndex,1000,0];private _g=[east]call Q_group;
 private _u=[_g,"FST_Droid_B1_AT",_p]call Q_unit;
 private _v=createVehicle["FST_Saber",_p vectorAdd[0,_range,0],[],0,"NONE"];createVehicleCrew _v;_v allowDamage false;
 {group _x setVariable["BURNS_exempt",true,true];group _x setVariable["FST_HC_blacklisted",true,true];_x disableAI "ALL";_x allowDamage false}forEach crew _v;
 _g setCombatMode "RED";[_g]call FST_HCSpawn_fnc_burnsApplyRole;_g reveal[_v,4];Q_at pushBack[_range,_u,_v];
}forEach[25,45,75];
Q_garrison=[];
{
 private _trial=_x;private _p=[1000+2000*_forEachIndex,4000,0];private _g=[east]call Q_group;
 private _u=[_g,"FST_Droid_B1_E5",_p]call Q_unit;_u setDir 180;[_g]call FST_HCSpawn_fnc_burnsApplyRole;
 _u disableAI "PATH";doStop _u;_u setVariable["FST_HC_ownsPath",true,true];_u setVariable["FST_HC_assignedPos",_p,true];
 _g setBehaviourStrong "COMBAT";_g setCombatMode "RED";
 if(!_trial)then{_g setVariable["BURNS_engagementNext",1e10]};
 private _t=[_p vectorAdd[0,60,0]]call Q_target;Q_garrison pushBack[_trial,_u,_t,_p];
}forEach[false,true];
Q_form=[];
{
 private _n=_x;private _p=[1000+3000*_forEachIndex,7000,0];private _g=[east]call Q_group;
 for "_i" from 0 to (_n-1)do{[_g,"FST_Droid_B1_E5",_p vectorAdd[(_i mod 6)*3.5,-4.5*floor(_i/6),0]]call Q_unit};
 private _t=[_p vectorAdd[0,100,0]]call Q_target;_g reveal[_t,4];_g setVariable["BURNS_b1DangerUntil",time+300];
 ["assault",_g,_p vectorAdd[0,200,0],500,[],2]call FST_HCSpawn_fnc_burnsCommand;
 Q_form pushBack[_n,_g,_t,_p];
}forEach[4,12];
Q_bx=[];
{
 private _mode=_x;private _p=[1000+3000*_forEachIndex,6000,0];private _g=[east]call Q_group;
 private _u=[_g,"FST_BX",_p]call Q_unit;Q_bx pushBack[_mode,_g,_u,_p,objNull];
}forEach["ambush","creep","cqb"];
Q_n99=createVehicle["FST_N99",[1000,5500,0],[],0,"NONE"];createVehicleCrew Q_n99;Q_n99 allowDamage false;
Q_ng=group driver Q_n99;Q_ng setVariable["FST_HC_blacklisted",true,true];
["BURNS_request",["assault",[Q_ng],[Q_n99],[1000,5700,0],500,[],2]]call CBA_fnc_serverEvent;
sleep 8;
{
 _x params["_mode","_g","_u","_p"];
 private _ok=[_mode,_g,_p vectorAdd[0,80,0],50,[],2]call FST_HCSpawn_fnc_burnsCommand;
 ["BX "+_mode+" accepted",_ok,_g getVariable["FST_HC_combatTask",[]]]call Q_check;
}forEach Q_bx;
sleep 12;
{
 _x params["_mode","_g","_u","_p"];
 if(_mode in ["creep","ambush"])then{["BX "+_mode+" prone requested",unitPos _u=="DOWN",[unitPos _u,stance _u,animationState _u]]call Q_check};
 if(_mode=="ambush")then{["Ambush holds fire",!(_u checkAIFeature "FIREWEAPON") && {(_u getVariable["Q_shots",0])==0}]call Q_check};
 private _t=[getPosATL _u vectorAdd[0,if(_mode=="cqb")then{10}else{35},0]]call Q_target;_g reveal[_t,4];_x set[4,_t];
}forEach Q_bx;
sleep 30;
{_x params["_range","_u","_v"];["AT fired rockets at "+str _range,(_u getVariable["Q_rockets",0])>0,[_u getVariable["Q_shots",0],_u getVariable["Q_first",-1],currentWeapon _u,_u distance _v]]call Q_check}forEach Q_at;
{_x params["_trial","_u","_t","_p"];["Garrison position preserved "+str _trial,!(_u checkAIFeature "PATH") && {_u distance2D _p<1},[_u distance2D _p,_u getVariable["Q_shots",0],_u knowsAbout _t,getDir _u]]call Q_check;
diag_log format["[AF_GARRISON] %1",[_trial,_u getVariable["Q_first",-1],_u getVariable["Q_shots",0],_u knowsAbout _t,getDir _u]]}forEach Q_garrison;
{
 _x params["_n","_g","_t","_p"];private _shots=0;private _orders=0;{_shots=_shots+(_x getVariable["Q_shots",0]);_orders=_orders+(_x getVariable["BURNS_formationOrderCount",0])}forEach units _g;
 ["B1 "+str _n+" shoots in contact",_shots>0,[_shots,_orders]]call Q_check;
 ["B1 "+str _n+" bounded formation orders",_orders<=_n*4,_orders]call Q_check;
 ["B1 "+str _n+" leader stays with firing squad",(leader _g distance2D _p)<25,[getPosATL leader _g,units _g apply{getPosATL _x}]]call Q_check;
}forEach Q_form;
{
 _x params["_mode","_g","_u","_p","_t"];
 if(_mode=="ambush")then{["Ambush opens weapons",(_g getVariable["BURNS_ambushTriggered",false]) && {_u checkAIFeature "FIREWEAPON"} && {(_u getVariable["Q_shots",0])>0},[_u getVariable["Q_shots",0],_u distance _t]]call Q_check};
 if(_mode=="cqb")then{["CQB reaches melee",!isNil{_u getVariable "BURNS_bxMeleeNext"},[_u distance _t,animationState _u,_u getVariable["BURNS_bxMeleeNext",-1]]]call Q_check};
 [_g,"stop"]call FST_HCSpawn_fnc_setCombatTask;
 ["BX "+_mode+" stop restores task writes",isNil{_u getVariable "BURNS_bxOwned"} && {_u checkAIFeature "FIREWEAPON"} && {_u checkAIFeature "PATH"},[unitPos _u,combatMode _g]]call Q_check;
}forEach Q_bx;
["N99 broker assault moves",Q_n99 distance2D[1000,5500,0]>50,[getPosATL Q_n99,Q_ng getVariable["FST_HC_combatTask",[]]]]call Q_check;
diag_log format["[AF_PHASE1_DONE] checks=%1 failed=%2",count Q_checks,{!(_x select 1)}count Q_checks];

// Actual rifle ammunition against a Saber, including an FST-held station.
Q_rifles=[];
{
 private _station=_x;private _p=[1000+2500*_forEachIndex,3500,0];private _g=[east]call Q_group;
 private _u=[_g,"FST_Droid_B1_E5",_p]call Q_unit;[_g]call FST_HCSpawn_fnc_burnsApplyRole;_g setCombatMode "RED";
 if(_station)then{_u disableAI "PATH";_u setVariable["FST_HC_ownsPath",true,true];_u setVariable["FST_HC_assignedPos",_p,true]};
 private _v=createVehicle["FST_Saber",_p vectorAdd[0,65,0],[],0,"NONE"];createVehicleCrew _v;_v allowDamage false;
 {group _x setVariable["BURNS_exempt",true,true];group _x setVariable["FST_HC_blacklisted",true,true];_x disableAI "ALL";_x allowDamage false}forEach crew _v;
 _g reveal[_v,4];_u doTarget driver _v;
 Q_rifles pushBack[_station,_u,_v,_g,_p];
}forEach[false,true];
sleep 25;
{_x params["_station","_u","_v","_g","_p"];["Rifle fires at Saber station="+str _station,(_u getVariable["Q_shots",0])>0,[_u getVariable["Q_shots",0],_g getVariable["BURNS_pointFire",[]],currentCommand _u]]call Q_check;
 if(_station)then{["Saber fire preserves station",!(_u checkAIFeature "PATH") && {_u distance2D _p<1}]call Q_check};
 // Reset must release an active assist without leaving a forced halt.
 ["reset",_g,_p,50,[],2]call FST_HCSpawn_fnc_burnsCommand;
 ["Rifle assist reset cleanup "+str _station,count(_g getVariable["BURNS_pointFire",[]])==0 && {isNil{_u getVariable "BURNS_pointFireLease"}}]call Q_check;
}forEach Q_rifles;
// Four real HC owner handoffs. No synthetic owner variable substitutes.
private _deadline=time+70;
waitUntil{sleep 1;count(allPlayers select{_x isKindOf "HeadlessClient_F"})>=4 || {time>_deadline}};
private _owners=(allPlayers select{_x isKindOf "HeadlessClient_F"})apply{owner _x};_owners=_owners arrayIntersect _owners;
["Four HCs joined",count _owners==4,_owners]call Q_check;
private _hg=[east]call Q_group;private _hu=[_hg,"FST_BX",[7500,7500,0]]call Q_unit;sleep 4;
{
 private _owner=_x;private _sent=_hg setGroupOwner _owner;diag_log format["[AF_TRANSFER_REQUEST] %1",[_owner,_sent,groupOwner _hg,units _hg apply{owner _x}]];
 private _key="Q_HC_AMBUSH_"+str _owner;[_hg,"ambush",_key]remoteExecCall["Q_hcAction",_owner];private _until=time+20;waitUntil{sleep 0.2;!isNil{missionNamespace getVariable _key} || {time>_until}};
 private _r=missionNamespace getVariable[_key,[]];
 ["HC ambush owns hold "+str _owner,count _r==7 && {(_r select 0)==_owner} && {!(_r select 4)} && {!(_r select 5)},_r]call Q_check;
 _hg setGroupOwner 2;private _until=time+20;waitUntil{sleep 0.2;(local _hg && {(units _hg findIf{!local _x})<0}) || {time>_until}};["stop",_hg,getPosATL _hu,50,[],2]call FST_HCSpawn_fnc_burnsCommand;sleep 3;
 ["HC to server stop releases "+str _owner,local _hg && {_hu checkAIFeature "PATH"} && {_hu checkAIFeature "FIREWEAPON"} && {isNil{_hu getVariable "BURNS_bxOwned"}},[unitPos _hu,groupOwner _hg]]call Q_check;
    ["HC stop posture restored "+str _owner,unitPos _hu=="AUTO",unitPos _hu]call Q_check;
}forEach _owners;
// Friendly and blocked enemies must not trigger concealed ambush.
private _ag=[east]call Q_group;private _au=[_ag,"FST_BX",[6000,2000,0]]call Q_unit;
private _friend=[_ag,"FST_BX",[6001,2000,0]]call Q_unit;sleep 4;
["ambush",_ag,[6000,2000,0],50,[],2]call FST_HCSpawn_fnc_burnsCommand;sleep 3;
["Ambush ignores friendly",!(_ag getVariable["BURNS_ambushTriggered",false])]call Q_check;
private _blocks=[];
 for "_i" from -1 to 1 do {for "_j" from 0 to 2 do {private _block=createVehicle["Land_CncWall4_F",[6000+_i*4,2010,_j*1.5],[],0,"CAN_COLLIDE"];_block setDir 0;_block setPosATL[6000+_i*4,2010,_j*1.5];_block allowDamage false;_blocks pushBack _block}};
 sleep 1;
private _bt=[[6000,2020,0]]call Q_target;_ag reveal[_bt,4];sleep 3;
// Friendly is moved to the same side of the wall so it cannot see round it.
["ambush",_ag,[6000,2000,0],50,[],2]call FST_HCSpawn_fnc_burnsCommand;sleep 3;
private _los=([_au,"VIEW",_bt]checkVisibility[eyePos _au,aimPos _bt]);
diag_log format["[AF_OCCLUSION_GEOMETRY] %1",[getPosASL _au,getPosASL _bt,eyePos _au,aimPos _bt,_blocks apply{[typeOf _x,getPosASL _x,boundingBoxReal _x]},lineIntersectsSurfaces[eyePos _au,aimPos _bt,_au,_bt,true,3,"VIEW","FIRE"]]];
["Ambush wall fixture blocks sight",_los<=0.5,_los]call Q_check;
["Ambush does not trigger through wall",!(_ag getVariable["BURNS_ambushTriggered",false]),_los]call Q_check;
["disable_group",_ag,getPosATL _au,50,[],2]call FST_HCSpawn_fnc_burnsCommand;
["BX disable releases owned holds",_au checkAIFeature "PATH" && {_au checkAIFeature "FIREWEAPON"}]call Q_check;
// Retest Assault crossing server-to-HC ownership with a real moving N99.
if(count _owners>0)then{
 private _start=getPosATL Q_n99;private _goal=_start vectorAdd[0,160,0];Q_ng setGroupOwner(_owners select 0);
 ["BURNS_request",["assault",[Q_ng],[Q_n99],_goal,500,[],2]]call CBA_fnc_serverEvent;
 sleep 35;
 diag_log format["[AF_N99_OWNER_DETAIL] %1",[local Q_n99,owner Q_n99,currentWaypoint Q_ng,waypoints Q_ng,crew Q_n99 apply{[typeOf _x,owner _x,getForcedSpeed _x,_x checkAIFeature "PATH",_x checkAIFeature "MOVE",currentCommand _x]}]];
 ["N99 owner-handoff Assault moves",Q_n99 distance2D _start>30,[groupOwner Q_ng,Q_n99 distance2D _start,_goal]]call Q_check;
};
diag_log format["[AF_DONE] checks=%1 failed=%2",count Q_checks,{!(_x select 1)}count Q_checks];
