	class FST_MK1Imploder_Exp_Soundset
	{
		soundShaders[]=
		{
			"FST_MK1Imploder_Explosion_Close",
			"FST_MK1Imploder_Explosion_Far"
		};
		volumeFactor=0.94999999;
		volumeCurve="InverseSquare2Curve";
		spatial=1;
		doppler=0;
		loop=0;
		soundShadersLimit=3;
		frequencyRandomizer=0.090000001;
		sound3DProcessingType="ExplosionLightTail3DProcessingType";
		distanceFilter="explosionTailDistanceFreqAttenuationFilter";
	};
	class FST_MK1Detonator_Exp_Soundset
	{
		soundShaders[]=
		{
			"FST_MK1Detonator_Explosion"
		};
		volumeFactor=2.1;
		volumeCurve="InverseSquare2Curve";
		spatial=1;
		doppler=1;
		loop=0;
		soundShadersLimit=3;
		frequencyRandomizer=0.090000001;
		sound3DProcessingType="ExplosionLightTail3DProcessingType";
		distanceFilter="explosionTailDistanceFreqAttenuationFilter";
	};
	class FST_C25Frag_Exp_Soundset
	{
		soundShaders[]=
		{
			"FST_C25Frag_Explosion"
		};
		volumeFactor=2.1;
		volumeCurve="InverseSquare2Curve";
		spatial=1;
		doppler=0;
		loop=0;
		soundShadersLimit=3;
		frequencyRandomizer=0.090000001;
		sound3DProcessingType="ExplosionLightTail3DProcessingType";
		distanceFilter="explosionTailDistanceFreqAttenuationFilter";
	};
	class FST_D19Concussion_Exp_Soundset
	{
		soundShaders[]=
		{
			"FST_D19Concussion_Explosion"
		};
		volumeFactor=3.1;
		volumeCurve="InverseSquare2Curve";
		spatial=1;
		doppler=1;
		loop=0;
		soundShadersLimit=3;
		frequencyRandomizer=0.090000001;
		sound3DProcessingType="ExplosionLightTail3DProcessingType";
		distanceFilter="explosionTailDistanceFreqAttenuationFilter";
	};
	class FST_SMK3_SmokeTrail_Soundset
	{
		soundShaders[]=
		{
			"FST_SMK_SmokeHiss"
		};
		volumeFactor=1.1;
		volumeCurve="InverseSquare2Curve";
		spatial=1;
		doppler=0;
		loop=1;
		soundShadersLimit=3;
		frequencyRandomizer=0.090000001;
		sound3DProcessingType="ExplosionLightTail3DProcessingType";
		distanceFilter="explosionTailDistanceFreqAttenuationFilter";
	};