removeallActions WeaponDroid1;
WeaponDroid1 addAction ["<t color='#ff1111'>WEAPONS</t>", hint ""]; 
WeaponDroid1 addAction ["<t color='#89CFF0'>-=GENERAL INFANTRY=-</t>", hint ""]; 
WeaponDroid1 addAction ["RIFLEMAN DC-15A","Scripts\Loadouts\Weaponry\Rifleman A.sqf"];  
WeaponDroid1 addAction ["RIFLEMAN DC-15S","Scripts\Loadouts\Weaponry\Rifleman S.sqf"]; 
WeaponDroid1 addAction ["RIFLEMAN DC-15C [60+ OP PTS]","Scripts\Loadouts\Weaponry\Rifleman C.sqf"];  
WeaponDroid1 addAction ["<t color='#89CFF0'>-=AMMO BEARER=-</t>", hint ""];
WeaponDroid1 addAction ["STD Ammo Bearer (Choose Weapon First)","Scripts\Loadouts\Weaponry\ABStandard.sqf"];
WeaponDroid1 addAction ["Z6 Ammo Bearer (Choose Weapon First)","Scripts\Loadouts\Weaponry\ABZ6.sqf"];
WeaponDroid1 addAction ["DC-15L Ammo Bearer (Choose Weapon First)","Scripts\Loadouts\Weaponry\AB15L.sqf"];
WeaponDroid1 addAction ["Standard AT Ammo Bearer (Choose Weapon First)","Scripts\Loadouts\Weaponry\ABAT.sqf"];
WeaponDroid1 addAction ["Guided AT Ammo Bearer (Choose Weapon First)","Scripts\Loadouts\Weaponry\ABGAT.sqf"];
WeaponDroid1 addAction ["Rifle AT Ammo Bearer (Choose Weapon First)","Scripts\Loadouts\Weaponry\ABRAT.sqf"];
WeaponDroid1 addAction ["<t color='#89CFF0'>-=SPECIALIZATIONS=-</t>", hint ""]; 
WeaponDroid1 addAction ["MEDIC DC-15S","Scripts\Loadouts\Weaponry\Medic.sqf"];
WeaponDroid1 addAction ["MEDIC DC-15A","Scripts\Loadouts\Weaponry\Medic15A.sqf"];
WeaponDroid1 addAction ["MEDIC DP-23","Scripts\Loadouts\Weaponry\MedicSCB.sqf"];
WeaponDroid1 addAction ["MEDIC DC-15C [60+ OP PTS]","Scripts\Loadouts\Weaponry\Medic15C.sqf"];  
WeaponDroid1 addAction ["MEDIC Backpack (Choose Weapon First)","Scripts\Loadouts\Weaponry\MedicBackpack.sqf"];
WeaponDroid1 addAction ["GRENADIER DC-15A","Scripts\Loadouts\Weaponry\Grenadier.sqf"];
WeaponDroid1 addAction ["GRENADIER DC-15S","Scripts\Loadouts\Weaponry\Grenadier15S.sqf"];
WeaponDroid1 addAction ["CBT ENGINEER (Choose Weapon First)","Scripts\Loadouts\Weaponry\CEngineer.sqf"];
WeaponDroid1 addAction ["EOD (Choose Weapon First)","Scripts\Loadouts\Weaponry\EOD.sqf"];
WeaponDroid1 addAction ["JTAC (Choose Weapon First)","Scripts\Loadouts\Weaponry\JTAC.sqf"];
WeaponDroid1 addAction ["CQC DP-23","Scripts\Loadouts\Weaponry\CQC.sqf"];
WeaponDroid1 addAction ["CQC DC-15S","Scripts\Loadouts\Weaponry\CQC15S.sqf"];
WeaponDroid1 addAction ["<t color='#89CFF0'>-=AUTOMATIC RIFLEMAN=-</t>", hint ""];
WeaponDroid1 addAction ["LMG GUNNER DC-15L","Scripts\Loadouts\Weaponry\Lmg.sqf"];
WeaponDroid1 addAction ["HEAVY GUNNER Z6","Scripts\Loadouts\Weaponry\Heavy.sqf"];
WeaponDroid1 addAction ["MARKSMAN","Scripts\Loadouts\Weaponry\DMR.sqf"];
WeaponDroid1 addAction ["<t color='#89CFF0'>-=ANTI-TANK=-</t>", hint ""];
WeaponDroid1 addAction ["LIGHT AT","Scripts\Loadouts\Weaponry\AT Light.sqf"];
WeaponDroid1 addAction ["LIGHT AT (Launcher Only)","Scripts\Loadouts\Weaponry\AT Light LauncherOnly.sqf"];
WeaponDroid1 addAction ["UNGUIDED AT DC-15S","Scripts\Loadouts\Weaponry\AT.sqf"];
WeaponDroid1 addAction ["UNGUIDED AT DC-15A","Scripts\Loadouts\Weaponry\AT15A.sqf"];
WeaponDroid1 addAction ["RIFLE AT","Scripts\Loadouts\Weaponry\RifleAT.sqf"];
WeaponDroid1 addAction ["GUIDED AT DC-15S","Scripts\Loadouts\Weaponry\AT Guided.sqf"];
WeaponDroid1 addAction ["GUIDED AT DC-15A","Scripts\Loadouts\Weaponry\AT Guided 15A.sqf"];
WeaponDroid1 addAction ["WIRE GUIDED AT DC-15S","Scripts\Loadouts\Weaponry\AT Wire_Guided.sqf"];
WeaponDroid1 addAction ["WIRE GUIDED AT DC-15A","Scripts\Loadouts\Weaponry\AT Wire_Guided 15A.sqf"];
WeaponDroid1 addAction ["<t color='#89CFF0'>-=EMPLACED WEAPONS=-</t>", hint ""];
WeaponDroid1 addAction ["E-WEB","Scripts\Loadouts\Weaponry\EWEB.sqf"];
WeaponDroid1 addAction ["Mortar","Scripts\Loadouts\Weaponry\Mortar.sqf"];
WeaponDroid1 addAction ["<t color='#89CFF0'>-=AIRBORNE INFANTRY=-</t>", hint ""]; 
WeaponDroid1 addAction ["RIFLEMAN DC-15A","Scripts\Loadouts\Weaponry\ABRifleman A.sqf"];  
WeaponDroid1 addAction ["RIFLEMAN DC-15S","Scripts\Loadouts\Weaponry\ABRifleman S.sqf"];
WeaponDroid1 addAction ["RIFLEMAN DC-15C [60+ OP PTS]","Scripts\Loadouts\Weaponry\ABRifleman C.sqf"];
WeaponDroid1 addAction ["GRENADIER DC-15A","Scripts\Loadouts\Weaponry\ABGrenadier.sqf"];
WeaponDroid1 addAction ["GRENADIER DC-15S","Scripts\Loadouts\Weaponry\ABGrenadier15S.sqf"];
WeaponDroid1 addAction ["CQC DP-23","Scripts\Loadouts\Weaponry\ABCQC.sqf"];
WeaponDroid1 addAction ["CQC DC-15S","Scripts\Loadouts\Weaponry\ABCQC15S.sqf"];
WeaponDroid1 addAction ["STD Ammo Bearer (Choose Weapon First)","Scripts\Loadouts\Weaponry\ABABStandard.sqf"];
WeaponDroid1 addAction ["DC-15L Ammo Bearer (Choose Weapon First)","Scripts\Loadouts\Weaponry\ABAB15L.sqf"];
WeaponDroid1 addAction ["Rifle AT Ammo Bearer (Choose Weapon First)","Scripts\Loadouts\Weaponry\ABABRAT.sqf"];
WeaponDroid1 addAction ["MEDIC Backpack (Choose Weapon First)","Scripts\Loadouts\Weaponry\ABMedicBackpack.sqf"];
WeaponDroid1 addAction ["JTAC (Choose Weapon First)","Scripts\Loadouts\Weaponry\ABJTAC.sqf"];
WeaponDroid1 addAction ["CBT ENGINEER (Choose Weapon First)","Scripts\Loadouts\Weaponry\ABEOD.sqf"];
WeaponDroid1 addAction ["LMG GUNNER DC-15L","Scripts\Loadouts\Weaponry\ABLmg.sqf"];
WeaponDroid1 addAction ["RIFLE AT","Scripts\Loadouts\Weaponry\ABRifleAT.sqf"];
WeaponDroid1 addAction ["<t color='#89CFF0'>-=AIRBORNE HOWLER=-</t>", hint ""];
WeaponDroid1 addAction ["HEAVY GUNNER Z6 (Airborne)","Scripts\Loadouts\Weaponry\ABHeavy.sqf"];
WeaponDroid1 addAction ["GUIDED AT DC-15S (Airborne)","Scripts\Loadouts\Weaponry\ABAT Guided.sqf"];
WeaponDroid1 addAction ["GUIDED AT DC-15A (Airborne)","Scripts\Loadouts\Weaponry\ABAT Guided 15A.sqf"];
WeaponDroid1 addAction ["WIRE GUIDED AT DC-15S (Airborne)","Scripts\Loadouts\Weaponry\ABAT Wire_Guided.sqf"];
WeaponDroid1 addAction ["WIRE GUIDED AT DC-15A (Airborne)","Scripts\Loadouts\Weaponry\ABAT Wire_Guided 15A.sqf"];
WeaponDroid1 addAction ["Z6 Ammo Bearer (Choose Weapon First)","Scripts\Loadouts\Weaponry\ABABZ6.sqf"];
WeaponDroid1 addAction ["Guided AT Ammo Bearer (Choose Weapon First)","Scripts\Loadouts\Weaponry\ABABGAT.sqf"];
WeaponDroid1 addAction ["<t color='#89CFF0'>-=ARF=-</t>", hint ""]; 
WeaponDroid1 addAction ["ARF Rifleman","Scripts\Loadouts\Weaponry\ARFRifleman.sqf"];
WeaponDroid1 addAction ["ARF Medic","Scripts\Loadouts\Weaponry\ARFMedic.sqf"];
WeaponDroid1 addAction ["ARF RTO","Scripts\Loadouts\Weaponry\ARFRTO.sqf"];
WeaponDroid1 addAction ["ARF Marksman (Valken 38X)","Scripts\Loadouts\Weaponry\ARFValken.sqf"];
WeaponDroid1 addAction ["ARF Marksman (DC-15X)","Scripts\Loadouts\Weaponry\ARF15X.sqf"];
WeaponDroid1 addAction ["<t color='#89CFF0'>-=FYNOCK=-</t>", hint ""];
WeaponDroid1 addAction ["PILOT DC-17","Scripts\Loadouts\Weaponry\Pilot.sqf"];
WeaponDroid1 addAction ["PILOT DC-15S","Scripts\Loadouts\Weaponry\Pilot15S.sqf"];
WeaponDroid1 addAction ["PILOT DC-15C [60+ OP PTS]","Scripts\Loadouts\Weaponry\Pilot15C.sqf"];
WeaponDroid1 addAction ["PILOT DP-23","Scripts\Loadouts\Weaponry\PilotSCB.sqf"];
WeaponDroid1 addAction ["CREWCHIEF DC-17","Scripts\Loadouts\Weaponry\CrewChief A.sqf"];
WeaponDroid1 addAction ["CREWCHIEF DC-15S","Scripts\Loadouts\Weaponry\CrewChief S.sqf"];
WeaponDroid1 addAction ["<t color='#89CFF0'>-=Secondary Weapons=-</t>", hint ""]; 
WeaponDroid1 addAction ["KNIFE","Scripts\Loadouts\Weaponry\Knife.sqf"];
WeaponDroid1 addAction ["PISTOL","Scripts\Loadouts\Weaponry\Pistol.sqf"];
WeaponDroid1 addAction ["DUAL PISTOLS (CS and above only)","Scripts\Loadouts\Weaponry\DualPistols.sqf"];
WeaponDroid1 addAction ["==================", hint ""];