params ["_node"];
private _check={params["_label","_pass",["_detail",[]]];diag_log format["[BXE_CHECK] %1",[_node,_label,_pass,_detail]]};
private _base=[3000+500*_node,6000,0];
private _g=createGroup[east,true];_g setVariable["FST_HC_noTransfer",true,true];
private _u=_g createUnit["FST_BX",_base,[],0,"NONE"];_u setVariable["BURNS_exempt",true,true];
private _sg=createGroup[west,true];_sg setVariable["FST_HC_noTransfer",true,true];
private _s=_sg createUnit["B_Soldier_F",_base vectorAdd[0,9,0],[],0,"NONE"];_s disableAI "ALL";_s allowDamage false;_s setVariable["IMS_IsUnitInvicibleScripted",true,true];
private _wall=createVehicle["Land_Cargo20_military_green_F",_base vectorAdd[0,4.5,0],[],0,"CAN_COLLIDE"];
_wall setDir 0;_wall setPosATL(_base vectorAdd[0,4.5,0]);
sleep 6;
_u setPosATL _base;_u setDir 0;_s setPosATL(_base vectorAdd[0,9,0]);
_u reveal[_s,4];_u setVariable["BURNS_exempt",false,true];_g setCombatMode "RED";
sleep 1;
private _los=[_u,"FIRE",_s]checkVisibility[eyePos _u,aimPos _s];
["solid obstruction prevents melee charge",_los<0.7 && {isNil{_u getVariable "BURNS_bxCharge"}},_los]call _check;
BURNS_BXMeleeEnabled=false;deleteVehicle _wall;sleep 1;
["melee setting disables opportunistic charge",isNil{_u getVariable "BURNS_bxCharge"}]call _check;
_u disableAI "PATH";BURNS_BXMeleeEnabled=true;sleep 1;
["external movement hold is respected",isNil{_u getVariable "BURNS_bxCharge"} && {!(_u checkAIFeature "PATH")}]call _check;
_u enableAI "PATH";
_g setVariable["FST_HC_heldBy",2,true];sleep 1;
["Zeus group hold is respected",isNil{_u getVariable "BURNS_bxCharge"}]call _check;
_g setVariable["FST_HC_heldBy",-1,true];
private _wp=_g addWaypoint[_base vectorAdd[100,0,0],0];_wp setWaypointType "MOVE";_wp setWaypointDescription "manual test order";_g setCurrentWaypoint _wp;sleep 1;
["manual movement order prevents opportunistic charge",isNil{_u getVariable "BURNS_bxCharge"}]call _check;
deleteWaypoint _wp;
[_s]joinSilent _g;sleep 1;
["friendly unit cannot become a charge target",isNil{_u getVariable "BURNS_bxCharge"}]call _check;
_u setVariable["BURNS_exempt",true,true];deleteVehicle _s;
removeAllWeapons _u;_u disableAI "AUTOCOMBAT";_g setBehaviourStrong "CARELESS";_g setSpeedMode "FULL";
_u setVariable["BURNS_exempt",false,true];_u doMove((getPosATL _u) vectorAdd[0,400,0]);
private _until=time+12;waitUntil{sleep 0.1;getAnimSpeedCoef _u>1.01 || {time>_until}};
["native run acquires boost",abs(getAnimSpeedCoef _u-1.15)<0.01,getAnimSpeedCoef _u]call _check;
// Every connected machine independently checks the replicated coefficient.
[_u,_node]remoteExec["Q_fnc_peerSpeed",0];sleep 1;
FST_HC_CombatTasksEnabled=false;sleep 0.6;
["global BURNS disable releases speed",abs(getAnimSpeedCoef _u-1)<0.01,getAnimSpeedCoef _u]call _check;
FST_HC_CombatTasksEnabled=true;_until=time+10;waitUntil{sleep 0.1;getAnimSpeedCoef _u>1.01 || {time>_until}};
["global BURNS reenable resumes boost",abs(getAnimSpeedCoef _u-1.15)<0.01,getAnimSpeedCoef _u]call _check;
_u setUnitPos "DOWN";sleep 2;
["prone excludes run boost",abs(getAnimSpeedCoef _u-1)<0.01,getAnimSpeedCoef _u]call _check;
_u setUnitPos "UP";_until=time+10;waitUntil{sleep 0.1;getAnimSpeedCoef _u>1.01 || {time>_until}};
_u setDamage 1;sleep 0.7;
["death releases speed even after WebKnight clears unit handlers",!alive _u && {abs(getAnimSpeedCoef _u-1)<0.01} && {isNil{_u getVariable "BURNS_bxSpeedOwned"}},[alive _u,getAnimSpeedCoef _u]]call _check;
deleteVehicle _u;sleep 0.7;
["deleted BX leaves the bounded owner roster",(BURNS_bxRoster findIf{isNull _x})<0,count BURNS_bxRoster]call _check;
diag_log format["[BXE_DONE] %1",[_node,clientOwner,"guards"]];
[_node]execVM "recovery.sqf";
