params ["_node"];
private _check={params["_label","_pass",["_detail",[]]];diag_log format["[BXS_FINAL_CHECK] %1",[_node,_label,_pass,_detail]]};
private _base=[3000+500*_node,6000,0];
private _g=createGroup[east,true];_g setVariable["FST_HC_noTransfer",true,true];
private _class=["FST_BX","FST_BX_Sniper","FST_BX_AT","FST_BX_AA","FST_BX_Rusty"]select _node;
private _u=_g createUnit[_class,_base,[],0,"NONE"];
_u disableAI "PATH";_u setDir 0;
_u addEventHandler["AnimStateChanged",{params["_u","_a"];if(_a in["bx_droid_roll_1","bx_droid_roll_2"] && {isNil{_u getVariable "Q_roll"}})then{_u setVariable["Q_roll",time]}}];
private _sg=createGroup[west,true];_sg setVariable["FST_HC_noTransfer",true,true];
private _s=_sg createUnit["B_Soldier_F",_base vectorAdd[0,1000,0],[],0,"NONE"];_s disableAI "ALL";
sleep 6;
private _health=_u getVariable["Droid_Health",-1];
private _deadline=time+8;
while{time<_deadline && {isNil{_u getVariable "Q_roll"}}}do{
 private _p=createVehicle["B_65x39_Caseless",_u modelToWorld[0.8,8,1.2],[],0,"CAN_COLLIDE"];
 _p setShotParents[_s,_s];_p setVelocity[0,-350,0];sleep 0.25;
};
["installed WebKnight dodge triggered",!isNil{_u getVariable "Q_roll"},[_class,clientOwner,animationState _u]]call _check;
_u enableAI "PATH";
[_g,"cqb",_base vectorAdd[0,80,0],100]call FST_HCSpawn_fnc_setCombatTask;
sleep 5;
private _task=[_g,["FST_HC_combatTask",[]]]call FST_HCSpawn_fnc_burnsStateGet;
["normal BURNS scheduler runs CQB",(_task param[0,""])=="cqb",_task]call _check;
["post-dodge crouch remains under WebKnight control",unitPos _u=="MIDDLE",[unitPos _u,animationState _u]]call _check;
["BX moves during native recovery",_u distance2D _base>1,_u distance2D _base]call _check;
private _until=(_u getVariable["Q_roll",time])+14;
waitUntil{sleep 0.25;time>=_until};
["WebKnight restores UP",unitPos _u=="UP",unitPos _u]call _check;
[_g,"stop"]call FST_HCSpawn_fnc_setCombatTask;sleep 2.5;
["stop does not restore a stale dodge crouch",unitPos _u=="UP",unitPos _u]call _check;
["CQB task releases owned state",isNil{_u getVariable "BURNS_bxOwned"} && {_u checkAIFeature "PATH"} && {_u checkAIFeature "FIREWEAPON"}]call _check;
[_g,"creep",(getPosATL _u)vectorAdd[0,25,0],50]call FST_HCSpawn_fnc_setCombatTask;sleep 3;
["creep still requests prone",unitPos _u=="DOWN",unitPos _u]call _check;
[_g,"stop"]call FST_HCSpawn_fnc_setCombatTask;sleep 2.5;
["creep releases its actual stance write",unitPos _u=="UP",unitPos _u]call _check;
[_g,"ambush",getPosATL _u,30]call FST_HCSpawn_fnc_setCombatTask;sleep 3;
["ambush still holds position and fire",unitPos _u=="DOWN" && {!(_u checkAIFeature "PATH")} && {!(_u checkAIFeature "FIREWEAPON")}]call _check;
[_g,"stop"]call FST_HCSpawn_fnc_setCombatTask;sleep 2.5;
["ambush releases movement fire and stance",unitPos _u=="UP" && {_u checkAIFeature "PATH"} && {_u checkAIFeature "FIREWEAPON"}]call _check;
["near-miss test preserves stock custom health",(_u getVariable["Droid_Health",-1])==_health,[_health,_u getVariable["Droid_Health",-1]] ]call _check;
deleteVehicle _u;deleteVehicle _s;
diag_log format["[BXS_FINAL_DONE] %1",[_node,clientOwner,_class]];
