params ["_node"];
private _check={params["_label","_pass",["_detail",[]]];diag_log format["[BXE_CHECK] %1",[_node,_label,_pass,_detail]]};
private _base=[3000+500*_node,6000,0];
private _class=["FST_BX","FST_BX_Sniper","FST_BX_AT","FST_BX_AA","FST_BX_Rusty"]select _node;
private _runners=[];
{
 private _g=createGroup[east,true];_g setVariable["FST_HC_noTransfer",true,true];_g setBehaviourStrong "CARELESS";_g setSpeedMode "FULL";
 private _u=_g createUnit[_x,_base vectorAdd[15*_forEachIndex,0,0],[],0,"NONE"];
 _u setDir 0;_u enableFatigue false;_u enableStamina false;_u setUnitPos "UP";removeAllWeapons _u;
 if(_forEachIndex==2)then{_u setVariable["BURNS_exempt",true,true]};
 _runners pushBack _u;
}forEach[_class,"O_Soldier_F",_class];
sleep 6;
["owner roster registers BX classes",(_runners select 0) in BURNS_bxRoster,[clientOwner,count BURNS_bxRoster]]call _check;
// Measure actual locomotion velocity during native running. Whole-route time
// also includes the engine's independent pauses at path segment boundaries.
{_x disableAI "AUTOCOMBAT";_x doMove((getPosATL _x) vectorAdd[0,450,0])}forEach _runners;
sleep 5;
private _start=_runners apply{getPosATL _x};
private _startTime=time;
private _speeds=[[],[],[]];
for "_i" from 1 to 200 do {sleep 0.1;{(_speeds select _forEachIndex)pushBack(abs speed _x)}forEach _runners;if(_i mod 20==0)then{diag_log format["[BXE_RUN] %1",[_node,time-_startTime,_runners apply{[getPosATL _x,animationState _x,getAnimSpeedCoef _x,abs speed _x]}]]}};
private _dist=[];{_dist pushBack(_x distance2D(_start select _forEachIndex))}forEach _runners;
private _steady=_speeds apply{_x sort true;_x select floor(0.95*(count _x-1))};
["BX runs faster than matched human",(_steady select 0)>(_steady select 1)*1.08,[_steady,_dist]]call _check;
["boosted BX outruns unmodified BX",(_steady select 0)>(_steady select 2)*1.08,[_steady,_dist]]call _check;
["human remains at native speed",abs(getAnimSpeedCoef(_runners select 1)-1)<0.01]call _check;
private _u=_runners select 0;
_u setVariable["BURNS_exempt",true,true];sleep 0.6;
["exemption restores run speed",abs(getAnimSpeedCoef _u-1)<0.01,getAnimSpeedCoef _u]call _check;
_u setVariable["BURNS_exempt",false,true];private _timeout=time+10;waitUntil{sleep 0.1;getAnimSpeedCoef _u>1.01 || {time>_timeout}};
["boost resumes after exemption",abs(getAnimSpeedCoef _u-1.15)<0.01,getAnimSpeedCoef _u]call _check;
[_u,1.35]remoteExecCall["setAnimSpeedCoef",0];sleep 0.6;
["external speed owns its coefficient",abs(getAnimSpeedCoef _u-1.35)<0.01 && {isNil{_u getVariable "BURNS_bxSpeedOwned"}},getAnimSpeedCoef _u]call _check;
[_u,1]remoteExecCall["setAnimSpeedCoef",0];sleep 0.2;_timeout=time+10;waitUntil{sleep 0.1;getAnimSpeedCoef _u>1.01 || {time>_timeout}};
["run boost resumes after native reset",abs(getAnimSpeedCoef _u-1.15)<0.01,getAnimSpeedCoef _u]call _check;
[_u,"bx_droid_sword"]remoteExec["switchMove",0];sleep 0.2;
["attack restores native animation timing",abs(getAnimSpeedCoef _u-1)<0.01,[animationState _u,getAnimSpeedCoef _u]]call _check;
sleep 3;
{deleteVehicle _x}forEach _runners;
// Real close-range pursuit, then repeated attacks against a stationary fixture.
private _g=createGroup[east,true];_g setVariable["FST_HC_noTransfer",true,true];_g setCombatMode "RED";
_u=_g createUnit[_class,_base,[],0,"NONE"];_u setDir 0;_u setVariable["BURNS_exempt",true,true];
private _sg=createGroup[west,true];_sg setVariable["FST_HC_noTransfer",true,true];
private _s=_sg createUnit["B_Soldier_F",_base vectorAdd[0,9,0],[],0,"NONE"];_s disableAI "ALL";_s allowDamage false;_s setVariable["IMS_IsUnitInvicibleScripted",true,true];
_u setVariable["Q_hits",[]];
_u addEventHandler["AnimStateChanged",{params["_u","_a"];if(_a in["bx_droid_sword","bx_droid_kick"])then{private _h=_u getVariable["Q_hits",[]];_h pushBack[time,_a,getAnimSpeedCoef _u];_u setVariable["Q_hits",_h]};diag_log format["[BXE_ANIM] %1",[clientOwner,time,_a,getAnimSpeedCoef _u]]}];
sleep 6;
_u setPosATL _base;_u setDir 0;_s setPosATL(_base vectorAdd[0,9,0]);_u setVariable["BURNS_exempt",false,true];
_u reveal[_s,4];_u doTarget _s;
private _begin=time;private _min=100;private _charged=false;
while{time<_begin+20}do{sleep 0.5;_min=_min min(_u distance _s);_charged=_charged || {!isNil{_u getVariable "BURNS_bxCharge"}};diag_log format["[BXE_CHASE] %1",[_node,time,_u distance _s,animationState _u,currentCommand _u,behaviour _u,_u checkAIFeature "PATH",_u checkAIFeature "AUTOCOMBAT",count(_u getVariable["BURNS_bxCharge",[]]),unitCombatMode _u]]};
private _hits=_u getVariable["Q_hits",[]];
["close enemy triggers melee commitment",_charged,[_min,_hits]]call _check;
["BX closes into melee reach",_min<3.2,_min]call _check;
["BX repeats melee attacks",count _hits>=3,_hits]call _check;
["melee animations are not sped up",count _hits>0 && {(_hits findIf{abs((_x select 2)-1)>0.01})<0},_hits]call _check;
// Changing tasks must release the temporary fire hold before saving task state.
[_g,"cqb",getPosATL _s,30]call FST_HCSpawn_fnc_setCombatTask;sleep 2;
[_g,"stop"]call FST_HCSpawn_fnc_setCombatTask;sleep 0.6;
["stop releases close-charge fire hold",_u checkAIFeature "FIREWEAPON" && {isNil{_u getVariable "BURNS_bxCharge"}}]call _check;
["stop restores automatic combat and engagement mode",_u checkAIFeature "AUTOCOMBAT" && {unitCombatMode _u==combatMode _g},[unitCombatMode _u,combatMode _g]]call _check;
_g setCombatMode "BLUE";_u setPosATL _base;_u setDir 0;sleep 3;
["hold fire prevents new melee commitment",isNil{_u getVariable "BURNS_bxCharge"}]call _check;
_g setCombatMode "RED";_s setCaptive true;sleep 1;
["captive target prevents melee commitment",isNil{_u getVariable "BURNS_bxCharge"}]call _check;
_s setCaptive false;_u setVariable["BURNS_exempt",true,true];sleep 0.6;
["exemption prevents melee commitment",isNil{_u getVariable "BURNS_bxCharge"} && {_u checkAIFeature "FIREWEAPON"}]call _check;
deleteVehicle _s;deleteVehicle _u;
diag_log format["[BXE_DONE] %1",[_node,clientOwner,_class]];
