
params ["_unit"];

if (!local _unit) exitWith {}; 

[_unit] spawn {

params ["_unit"];

sleep 0.1;

list_41allheads = [
	"TCGM_Fem_Zhu",
	"TCGM_MakF_ZhuClub1",
	"TCGM_Fem_Stone",
	"TCGM_Fem_StoneBun",
    "TCGM_MakF_StoneClub1",
	"TCGM_Fem_Fox",
	"TCGM_Fem_FoxBun",
    "TCGM_MakF_FoxClub1",
	"TCGM_Fem_Eilish",
	"TCGM_Fem_EilishBun",
    "TCGM_MakF_EilishClub1",
	"TCGM_Fem_Ayres",
	"TCGM_MakF_AyresClub1",
	"TCGM_Fem_Portman",
	"TCGM_MakF_PortmanClub1",
	"TCGM_Fem_Lynch",
	"TCGM_MakF_LynchClub1",
	"TCGM_Fem_Liu",
	"TCGM_MakF_LiuClub1",
	"TCGM_Fem_Hobson",
	"TCGM_MakF_HobsonClub1",
	"TCGM_Fem_Gonzalez",
	"TCGM_MakF_GonzalezClub1",
	"TCGM_Fem_Fenty",
	"TCGM_MakF_FentyClub1",
	"FST_Navy_Face_Ruby",
	"FST_Navy_Face_Mustang",
	"GreekHead_A3_01",
	"GreekHead_A3_02",
	"GreekHead_A3_03",
    "GreekHead_A3_04",
    "GreekHead_A3_05",
    "GreekHead_A3_06",
    "GreekHead_A3_07",
    "GreekHead_A3_08",
    "GreekHead_A3_09",
    "GreekHead_A3_11",
    "GreekHead_A3_12",
    "GreekHead_A3_13",
    "GreekHead_A3_14",
	"PersianHead_A3_01",
	"PersianHead_A3_02",
	"PersianHead_A3_03",
	"WhiteHead_01",
    "WhiteHead_02",
	"WhiteHead_03",
	"WhiteHead_04",
	"WhiteHead_05",
	"WhiteHead_06",
	"WhiteHead_07",
	"WhiteHead_08",
	"WhiteHead_09",
	"WhiteHead_10",
	"WhiteHead_11",
	"WhiteHead_12",
	"WhiteHead_13",
	"WhiteHead_14",
	"WhiteHead_15",
	"WhiteHead_16",
	"WhiteHead_17",
	"WhiteHead_18",
	"WhiteHead_19",
	"WhiteHead_20",
	"WhiteHead_21",
	"WhiteHead_23",
	"WhiteHead_24",
	"WhiteHead_25",
	"WhiteHead_26",
	"WhiteHead_27",
	"WhiteHead_28",
	"WhiteHead_29",
	"WhiteHead_30",
	"WhiteHead_31",
	"WhiteHead_32",
	"RussianHead_1",
	"RussianHead_2",
	"RussianHead_3",
	"RussianHead_4",
	"RussianHead_5",
    "AfricanHead_01",
    "AfricanHead_02",
    "AfricanHead_03",
	"LivonianHead_1",
	"LivonianHead_2",
	"LivonianHead_3",
	"LivonianHead_4",
	"LivonianHead_5",
	"LivonianHead_6",
	"LivonianHead_7",
	"LivonianHead_8",
	"LivonianHead_9",
	"LivonianHead_10",
	"AsianHead_A3_01",
	"AsianHead_A3_02",
	"AsianHead_A3_03",
	"AsianHead_A3_04",
	"AsianHead_A3_05",
	"AsianHead_A3_06",
	"AsianHead_A3_07",
	"TanoanHead_A3_01",
	"TanoanHead_A3_02",
	"TanoanHead_A3_03",
	"TanoanHead_A3_04",
	"TanoanHead_A3_05",
	"TanoanHead_A3_06",
	"TanoanHead_A3_07",
	"TanoanHead_A3_08",
	"Mavros",
	"Sturrock",
	"Barklem",
	"Ioannou",
	"Head_AbedDark",
	"Head_AbedGrey",
	"Head_AbedPink",
	"Head_AbedYellow",
	"Head_AqualishBrown",
	"Head_AqualishGreen",
	"Head_AqualishLight",
	"Head_DurosBlue",
	"Head_DurosBlue2",
	"Head_DurosGreen",
	"Head_DurosBGrey",
	"Head_IshiGreen",
	"Head_IshiGreen2",
	"Head_IshiGreen3",
	"Head_IshiOlive",
	"Head_IshiYellow",
	"Head_KeldorYelLow",
	"Head_MimbaneseDark",
	"Head_MimbaneseLines",
	"Head_MimbaneseOrange",
	"Head_MimbaneseRed",
	"Head_NiktoBrown",
	"Head_NiktoBrown2",
	"Head_NiktoDark",
	"Head_NiktoGreen",
	"Head_NiktoGrey",
	"Head_NiktoOrange",
	"Head_QuarrenBrown",
	"Head_QuarrenPink",
	"Head_QuarrenRed",
	"Head_QuarrenYellow",
	"Head_RodianBlue",
	"Head_RodianGreen",
	"Head_RodianOlive",
	"Head_RodianRed",
	"Head_RodianYellow",
	"Head_SullustanGreen",
	"Head_SullustanGrey",
	"Head_SullustanOrange",
	"Head_SullustanSkin",
	"Head_WeequayBrown",
	"Head_WeequayDark",
	"Head_WeequayGrey",
	"Head_WeequayBod",
	"ls_mirialan_male1_green",
	"ls_mirialan_male1_sand",
	"ls_mirialan_male1_yellow",
	"ls_mirialan_male2_green",
	"ls_mirialan_male2_sand",
	"ls_mirialan_male2_yellow",
	"ls_mirialan_male3_green",
	"ls_mirialan_male3_sand",
	"ls_mirialan_male3_yellow",
	"ls_zabrak_male2t0_base",
	"ls_zabrak_male1t0_orange",
	"ls_zabrak_male2t0_orange",
	"ls_zabrak_male1t0_pale",
	"ls_zabrak_male2t0_pale",
	"ls_zabrak_male1t0_red",
	"ls_zabrak_male2t0_red"
];

private _chosenhead = selectRandom list_41allheads;

[_unit, _chosenhead] remoteExec ["setFace", 0, _unit];
[_unit, "ACE_NoVoice"] remoteExec ["setSpeaker", 0, _unit];
[_unit, "CIS Prisoner"] remoteExec ["setName", 0, _unit];
removeGoggles _unit;
[_unit, true] call ace_captives_fnc_setHandcuffed;

};