params ["_node"];
private _check={params["_label","_pass",["_detail",[]]];diag_log format["[B2L_CHECK] %1",[_node,_label,_pass,_detail]]};
private _base=[3000+500*_node,6000,0];
private _g=createGroup[east,true];_g setVariable["FST_HC_noTransfer",true,true];_g setFormation "WEDGE";_g setCombatMode "RED";
for "_i" from 0 to 3 do {private _u=_g createUnit[if(_i==0)then{"FST_B2_TL"}else{"FST_B2"},_base vectorAdd[2*_i,0,0],[],0,"NONE"];_u setDir 0};
private _sg=createGroup[west,true];_sg setVariable["FST_HC_noTransfer",true,true];
private _s=_sg createUnit["B_Soldier_F",_base vectorAdd[0,1000,0],[],0,"NONE"];_s disableAI "ALL";_s allowDamage false;
sleep 7;
["no nearby known contact leaves native formation",formation _g=="WEDGE" && {isNil{_g getVariable "BURNS_b2Line"}}]call _check;
private _health=(units _g)apply{[_x,_x getVariable["Droid_Health",-1]]};
_s setPosATL(_base vectorAdd[0,150,0]);{_x reveal[_s,4]}forEach units _g;sleep 3;
["known visible enemy starts formation",formation _g=="LINE" && {!isNil{_g getVariable "BURNS_b2Line"}}]call _check;
_g setVariable["BURNS_exempt",true,true];sleep 2;
["group exemption restores formation and fire rules",formation _g=="WEDGE" && {combatMode _g=="RED"} && {isNil{_g getVariable "BURNS_b2Line"}}]call _check;
_g setVariable["BURNS_exempt",false,true];sleep 2;
private _u=(units _g)select 1;_u setVariable["BURNS_exempt",true,true];sleep 2;
["individual exemption releases line",isNil{_g getVariable "BURNS_b2Line"}]call _check;
_u setVariable["BURNS_exempt",false,true];sleep 2;
_u disableAI "PATH";sleep 2;
["external path hold releases line without re-enabling movement",isNil{_g getVariable "BURNS_b2Line"} && {!(_u checkAIFeature "PATH")}]call _check;
_u enableAI "PATH";sleep 2;
_g setVariable["FST_HC_heldBy",2,true];sleep 2;
["Zeus hold releases line",isNil{_g getVariable "BURNS_b2Line"}]call _check;
_g setVariable["FST_HC_heldBy",-1,true];sleep 2;
FST_HC_CombatTasksEnabled=false;sleep 2;
["global BURNS disable restores group",isNil{_g getVariable "BURNS_b2Line"} && {formation _g=="WEDGE"}]call _check;
FST_HC_CombatTasksEnabled=true;sleep 2;
BURNS_B2LineEnabled=false;sleep 2;
["B2 setting disable restores group",isNil{_g getVariable "BURNS_b2Line"}]call _check;
BURNS_B2LineEnabled=true;sleep 2;
[_g,"retreat",_base vectorAdd[0,-100,0],50]call FST_HCSpawn_fnc_setCombatTask;sleep 2;
["BURNS retreat is not converted into an advance",isNil{_g getVariable "BURNS_b2Line"}]call _check;
[_g,"hunt",getPosATL _s,100]call FST_HCSpawn_fnc_setCombatTask;sleep 3;
["BURNS advance order permits line",!isNil{_g getVariable "BURNS_b2Line"}]call _check;
[_g,"stop"]call FST_HCSpawn_fnc_setCombatTask;sleep 2;
["stop prevents immediate automatic restart",isNil{_g getVariable "BURNS_b2Line"}]call _check;
_g setVariable["BURNS_b2TaskIntent","",true];
private _wp=_g addWaypoint[getPosATL leader _g,0];_wp setWaypointType "HOLD";_wp setWaypointDescription "manual hold";_g setCurrentWaypoint _wp;sleep 2;
["manual HOLD waypoint remains in control",isNil{_g getVariable "BURNS_b2Line"}]call _check;
deleteWaypoint _wp;
private _mixed=_g createUnit["O_Soldier_F",_base,[],0,"NONE"];sleep 2;
["mixed non-B2 group is not overridden",isNil{_g getVariable "BURNS_b2Line"}]call _check;
deleteVehicle _mixed;sleep 2;
["Flame B2 vehicle and module classes removed",!isClass(configFile>>"CfgVehicles">>"FST_B2_Flame") && {!isClass(configFile>>"CfgVehicles">>"FST_HC_Module_b2_flame_team")}]call _check;
["Flame B2 spawn template removed",isNil{FST_HC_Templates get "b2_flame_team"}]call _check;
["normal B2 group resumes after mixed unit removal",!isNil{_g getVariable "BURNS_b2Line"}]call _check;
["native AI features and animation speed are untouched",((units _g)findIf{!(_x checkAIFeature "ANIM") || {!(_x checkAIFeature "PATH")} || {!(_x checkAIFeature "MOVE")} || {!(_x checkAIFeature "FIREWEAPON")} || {!(_x checkAIFeature "AUTOCOMBAT")} || {getAnimSpeedCoef _x!=1}})<0]call _check;
["stock WebKnight health is unchanged",(_health findIf{(_x select 0)getVariable["Droid_Health",-1]!=(_x select 1)})<0,_health apply{(_x select 0)getVariable["Droid_Health",-1]}]call _check;
private _oldLeader=leader _g;_oldLeader setDamage 1;
private _promotionDeadline=time+40;waitUntil{sleep 1;leader _g!=_oldLeader || {time>_promotionDeadline}};sleep 3;
["leader casualty safely rebuilds surviving line",leader _g!=_oldLeader && {!isNil{_g getVariable "BURNS_b2Line"}},[count(units _g select{alive _x}),alive leader _g,leader _g==_oldLeader,formation _g,combatMode _g,_g getVariable["BURNS_b2Line",[]]]]call _check;
_s setPosATL(_base vectorAdd[0,1000,0]);sleep 13;
["lost contact restores native group controls",isNil{_g getVariable "BURNS_b2Line"} && {formation _g=="WEDGE"},[formation _g,combatMode _g,count(_g getVariable["BURNS_b2Line",[]])]]call _check;
{deleteVehicle _x}forEach units _g;deleteVehicle _oldLeader;deleteVehicle _s;
diag_log format["[B2L_DONE] %1",[_node,clientOwner,"guards"]];
