params["_node"];
private _check={params["_label","_pass",["_detail",[]]];diag_log format["[GUL_CHECK] %1",[_node,_label,_pass,_detail]]};
private _base=[13000+_node*450,15400,0];
private _g=createGroup[east,true];_g setVariable["FST_HC_noTransfer",true,true];
private _u=_g createUnit[["JMSEF_animals_varren_o","JMSEF_animals_var_bers_o","JMSEF_animals_var_alpha_o"]select(_node mod 3),_base,[],0,"NONE"];_u allowDamage false;_u setDir 0;
private _tg=createGroup[west,true];_tg setVariable["FST_HC_noTransfer",true,true];_tg setVariable["BURNS_exempt",true,true];
private _t=_tg createUnit["B_Soldier_F",_base vectorAdd[0,80,0],[],0,"NONE"];_t allowDamage false;_t disableAI "ALL";
sleep 8;_g reveal[_t,4];sleep 3;
private _health=damage _u;
private _release={!(animationState _u in["burns_gulanthar_run","burns_gulanthar_climb"])};
{
 _x params["_object","_variable","_value","_restore","_label"];
 _object setVariable[_variable,_value,true];sleep 1;
 [_label,call _release,[animationState _u]]call _check;
 _object setVariable[_variable,_restore,true];_t setPosATL((getPosATL _u)vectorAdd[0,80,0]);_g reveal[_t,4];sleep 2;
}forEach[[_u,"BURNS_exempt",true,false,"unit exemption releases"],[_g,"FST_HC_heldBy",2,-1,"Zeus hold releases"]];
BURNS_GulantharRunEnabled=false;sleep 1;["run setting releases",call _release]call _check;BURNS_GulantharRunEnabled=true;sleep 2;
FST_HC_CombatTasksEnabled=false;sleep 1;["global disable releases",call _release]call _check;FST_HC_CombatTasksEnabled=true;sleep 2;
_u disableAI "ANIM";_u switchMove "form939_attack4";sleep 0.2;
["native attack ANIM lock preserved",!(_u checkAIFeature "ANIM") && {animationState _u=="form939_attack4"},animationState _u]call _check;
sleep 1;_u enableAI "ANIM";
_u disableAI "ANIM";_u switchMove "form939_eat";sleep 0.3;
["eating is not interrupted",!(_u checkAIFeature "ANIM") && {animationState _u=="form939_eat"},animationState _u]call _check;
_u enableAI "ANIM";_u switchMove "form939_idle";sleep 1;
private _wp=_g addWaypoint[(getPosATL _u)vectorAdd[0,-100,0],0];_wp setWaypointType "MOVE";_wp setWaypointDescription "manual move";_g setCurrentWaypoint _wp;sleep 1;
["manual waypoint releases",call _release]call _check;deleteWaypoint _wp;
[_g,"retreat",_base,100]call FST_HCSpawn_fnc_setCombatTask;sleep 1;["retreat releases pursuit assistance",call _release]call _check;
[_g,"stop"]call FST_HCSpawn_fnc_setCombatTask;sleep 1;["stop prevents pursuit assistance",call _release]call _check;
[_g,"hunt",getPosATL _t,100]call FST_HCSpawn_fnc_setCombatTask;sleep 2;
["hunt restores pursuit intent",(_g getVariable["BURNS_creatureTaskIntent",""])=="hunt"]call _check;
_u forceSpeed 0;sleep 1;["external forced stop preserved",getForcedSpeed _u==0 && {call _release}]call _check;_u forceSpeed 15;
_t setPosATL(_u modelToWorld[0,2,0]);_u setVariable["psych",false];sleep 1;
private _attack=[];
for "_i" from 1 to 80 do {sleep 0.1;_attack pushBack[animationState _u,_u checkAIFeature "ANIM",getAnimSpeedCoef _u]};
["native melee still starts",(_attack findIf{((_x select 0)find "form939_attack")==0})>=0,{((_x select 0)find "form939_attack")==0}count _attack]call _check;
["attack playback speed unchanged",(_attack findIf{(_x select 2)!=1})<0]call _check;
["health unchanged",damage _u==_health,[damage _u,_health]]call _check;
_u allowDamage true;_u setDamage 1;sleep 2;
["death animation not replaced",!alive _u && {call _release},animationState _u]call _check;
deleteVehicle _u;deleteVehicle _t;deleteGroup _g;deleteGroup _tg;
diag_log format["[GUL_GUARDS_DONE] %1",[_node,clientOwner]];
