if(!isServer)exitWith{};
Q_checks=[];Q_check={params["_name","_pass",["_data",[]]];Q_checks pushBack[_name,_pass,_data];diag_log format["[MEAP_CHECK] %1",[_name,_pass,_data]]};
sleep 15;
{["addon "+_x,isClass(configFile>>"CfgPatches">>_x)]call Q_check}forEach["MEAP_Core","MEAP_Economy_Core","MEAP_SW_Core","MEAP_SW_Props","MEAP_SW_Structures","MEAP_Architect_Core"];
{["function "+_x,!isNil _x]call Q_check}forEach["MEAP_fnc_requestArchitectMode","MEAP_fnc_architectServerAction","MEAP_fnc_openArchitectMode","MEAP_fnc_applySnapTransform"];
["construction palette initialized",count MEAP_Architect_allowedClasses>=20,MEAP_Architect_allowedClasses]call Q_check;
private _models=[];
{private _cfg=configFile>>"CfgVehicles">>_x;private _model=getText(_cfg>>"model");if(_model select [0,4]=="MEAP" || {_model select [0,5]=="\MEAP"})then{_models pushBack[_x,_model,fileExists _model]}}forEach MEAP_Architect_allowedClasses;
["custom construction models resolve",count _models>0 && {_models findIf {!(_x select 2)}<0},_models]call Q_check;
{private _probe=createVehicle[_x select 0,[2000,2000,50],[],0,"CAN_COLLIDE"];diag_log format["[MEAP_MODEL_ANCHORS] %1",[typeOf _probe,selectionNames _probe,_probe selectionNames "Memory",allLODs _probe]];deleteVehicle _probe}forEach _models;
private _deadline=diag_tickTime+160;waitUntil{sleep 1;count((entities "HeadlessClient_F")select{isPlayer _x && {owner _x>2}})>=4 || diag_tickTime>_deadline};
sleep 10;
private _clients=(entities "HeadlessClient_F")select{isPlayer _x && {owner _x>2}};
["remote player proxies available",count _clients>=2,_clients apply {[isPlayer _x,owner _x,alive _x]}]call Q_check;
if(count _clients<2)exitWith{diag_log format["[MEAP_DONE] checks=%1 failures=%2",count Q_checks,Q_checks select{!(_x select 1)}]};
private _u=_clients select 0;private _other=_clients select 1;private _owner=owner _u;private _key=[_u]call MEAP_fnc_getArchitectKey;
private _req={params["_action",["_payload",[]],["_tokenOverride",""]];private _t=if(_tokenOverride=="")then{_token}else{_tokenOverride};["ACTION",[_action,_u,_t,_payload]]remoteExecCall["Q_fnc_request",_owner];sleep 0.7;};
["OPEN",[_u]]remoteExecCall["Q_fnc_request",_owner];sleep 1;
["unassigned client denied",isNil {MEAP_Architect_sessions get str _owner}]call Q_check;
MEAP_Architect_grants set[_key,true];
["server recognizes explicit grant",[_u]call MEAP_fnc_isArchitectEligible,[_key,MEAP_Architect_grants]]call Q_check;
["REALOPEN",[_u]]remoteExecCall["Q_fnc_request",_owner];sleep 1;
["production rejects headless sender zero",isNil {MEAP_Architect_sessions get str _owner}]call Q_check;
["OPEN",[_u]]remoteExecCall["Q_fnc_request",_owner];sleep 2;
private _session=MEAP_Architect_sessions getOrDefault[str _owner,[]];
["assigned client session accepted",count _session==2,_session]call Q_check;
if(count _session!=2)exitWith{diag_log format["[MEAP_DONE] checks=%1 failures=%2",count Q_checks,Q_checks select{!(_x select 1)}]};
private _token=_session select 1;private _class="MEAP_SW_Props_Common_DuracreteBarrierOne_NoFiringPort";
["REALCLOSE",[_u,true]]remoteExecCall["Q_fnc_request",owner _other];sleep 1;
["production rejects foreign headless close",!isNil {MEAP_Architect_sessions get str _owner}]call Q_check;
["FOREIGNCLOSE",[_u,true]]remoteExecCall["Q_fnc_request",owner _other];sleep 1;
["foreign client cannot force close",!isNil {MEAP_Architect_sessions get str _owner}]call Q_check;
private _pos=(getPosASL _u)vectorAdd[10,0,2];private _vectors=[[0,1,0],[0,0,1]];
private _owned={(allMissionObjects _class)select{(_x getVariable["MEAP_Architect_constructedBy",""])==_key}};
private _payload=[_class,_pos,_vectors,objNull,"","",false];
["CREATE",_payload,"invalid-token"]call _req;["invalid token rejected",count(call _owned)==0]call Q_check;
["ACTION",["CREATE",_u,_token,_payload]]remoteExecCall["Q_fnc_request",owner _other];sleep 1;["spoofed owner rejected",count(call _owned)==0]call Q_check;
["CREATE",["B_MBT_01_cannon_F",_pos,_vectors]]call _req;["non-whitelisted class rejected",MEAP_Architect_objectCounts getOrDefault[_key,0]==0]call Q_check;
["CREATE",[_class,_pos vectorAdd[200,0,0],_vectors]]call _req;["outside radius rejected",count(call _owned)==0]call Q_check;
private _before=MEAP_Architect_budgetBalances get _key;private _cost=[_class]call MEAP_fnc_getArchitectBuildCost;
["CREATE",_payload]call _req;private _objects=call _owned;["remote placement accepted",count _objects==1]call Q_check;
if(count _objects!=1)exitWith{diag_log format["[MEAP_DONE] checks=%1 failures=%2",count Q_checks,Q_checks select{!(_x select 1)}]};
private _obj=_objects select 0;
["placement charged once",MEAP_Architect_budgetBalances get _key==_before-_cost]call Q_check;
["server owns construction",local _obj]call Q_check;
["LOCK",[_obj]]call _req;["owner edit lock acquired",!isNil {MEAP_Architect_editLocks get netId _obj}]call Q_check;
private _move=_pos vectorAdd[4,0,0];["EDIT",[_obj,_move,_vectors]]call _req;
["edit moves object",(getPosASL _obj)distance _move<0.1,getPosASL _obj]call Q_check;
["UNDO"]call _req;["undo edit restores position",(getPosASL _obj)distance _pos<0.1]call Q_check;
["CAPTURE",[_obj]]call _req;["saved blueprint captured",count MEAP_Architect_blueprints>=2,keys MEAP_Architect_blueprints]call Q_check;
["DELETE",[_obj]]call _req;["delete refunds and removes",isNull _obj && {MEAP_Architect_budgetBalances get _key==_before} && {MEAP_Architect_objectCounts getOrDefault[_key,0]==0}]call Q_check;
["UNDO"]call _req;["undo delete restores and recharges",count(call _owned)==1 && {MEAP_Architect_budgetBalances get _key==_before-_cost}]call Q_check;
_obj=(call _owned)select 0;["DELETE",[_obj]]call _req;
private _draft=+_payload;_draft set[6,true];["CREATE",_draft]call _req;_obj=(call _owned)param[0,objNull];
["draft is globally hidden",!isNull _obj && {isObjectHidden _obj} && {_obj getVariable["MEAP_Architect_draft",false]}]call Q_check;
["PUBLISH",[_obj]]call _req;["publish reveals draft without new charge",!isObjectHidden _obj && {!(_obj getVariable["MEAP_Architect_draft",true])} && {MEAP_Architect_budgetBalances get _key==_before-_cost}]call Q_check;
MEAP_Architect_budgetBalances set[_key,0];["CREATE",_payload]call _req;["insufficient budget rejected",count(call _owned)==1]call Q_check;
MEAP_Architect_budgetBalances set[_key,100];MEAP_Architect_maxObjects=1;["CREATE",_payload]call _req;["object limit enforced",count(call _owned)==1]call Q_check;MEAP_Architect_maxObjects=100;
["DELETE",[_obj]]call _req;
private _blueprintBefore=MEAP_Architect_budgetBalances get _key;
["PLACEBLUEPRINT",["CFG:MEAP_Daidalos_BarrierPair",_pos,90,false]]call _req;
private _pair=call _owned;
["two-piece blueprint placed",count _pair==2]call Q_check;
["blueprint charged total cost",MEAP_Architect_budgetBalances get _key==_blueprintBefore-2*_cost]call Q_check;
if(count _pair==2)then{
 ["blueprint preserves spacing",abs(((_pair select 0)distance(_pair select 1))-4)<0.1]call Q_check;
 private _points=((_pair select 0) selectionNames "Memory") select{(toLower _x)find "meap_snappoint_"==0};
 if(count _points>=2)then{
  ["snapping helper recognizes anchored barrier",[_pair select 0]call MEAP_fnc_isSnappable]call Q_check;
  private _a=_pair select 0;private _b=_pair select 1;private _pa=_points select 0;private _pb=_points select 1;
  private _snapped=[_a,_b,_pa,_pb]call MEAP_fnc_applySnapTransform;
  ["snap joins model anchors",_snapped && {(_a modelToWorldWorld(_a selectionPosition[_pa,"Memory"]))distance(_b modelToWorldWorld(_b selectionPosition[_pb,"Memory"]))<0.02}]call Q_check;
 }else{
  diag_log "[MEAP_LIMITATION] Supplied barrier model has no snap anchors; positive snapping is unavailable, not qualified.";
  private _a=_pair select 0;private _b=_pair select 1;private _original=getPosWorld _a;
  ["unanchored barrier is not advertised as snappable",!([_a]call MEAP_fnc_isSnappable)]call Q_check;
  private _snapped=[_a,_b,"MEAP_SnapPoint_Left","MEAP_SnapPoint_Right"]call MEAP_fnc_applySnapTransform;
  ["missing anchors rejected without moving object",!_snapped && {(getPosWorld _a)distance _original<0.02}]call Q_check;
 };
};
private _pairBalance=MEAP_Architect_budgetBalances get _key;
["PLACEBLUEPRINT",["CFG:MEAP_Daidalos_BarrierPair",(getPosASL _u)vectorAdd[49,0,0],0,false]]call _req;
["out-of-bounds blueprint rejected atomically",count(call _owned)==2 && {MEAP_Architect_budgetBalances get _key==_pairBalance}]call Q_check;
{["DELETE",[_x]]call _req}forEach(call _owned);
["CREATE",_payload]call _req;
MEAP_Architect_grants deleteAt _key;sleep 3;["revocation closes session",isNil{MEAP_Architect_sessions get str _owner}]call Q_check;
["CREATE",_payload]call _req;["revoked session cannot build",count(call _owned)==1]call Q_check;
{deleteVehicle _x}forEach(call _owned);
diag_log format["[MEAP_DONE] checks=%1 failures=%2",count Q_checks,Q_checks select{!(_x select 1)}];
